### ISSUE TITLE
Add Realtime API for favoriting rooms

### ISSUE THREAD

**Issue by Shailesh351** [RocketChat/Rocket.Chat.Kotlin.SDK#117]
**Actual behaviour**
- Currently sdk is missing API for adding or removing room to/from favorites

**Expected behaviour**
- Add API for it

Reference : https://rocket.chat/docs/developer-guides/realtime-api/method-calls/favoriting-rooms/

**Comment by rafaelks** [comment]
@Shailesh351 Why do you think this needs to be a RealTime API and not REST?

**Comment by Shailesh351** [comment]
@rafaelks I checked docs there is no rest api for it. also using realtime api is fast as compared to rest i guess.

**Comment by rafaelks** [comment]
@Shailesh351 If there's no REST API for that, please open a feature request in our forums requesting that: https://forums.rocket.chat/c/feature-requests (you can mention me on the feature request you want).

There's no reason to use RealTime on this call, because it doesn't depend on the RealTime connection in order to work. RealTime methods will only be implemented when it makes sense for a RealTime thing (status of the user, for example).

Gonna close the issue for now, thank you @Shailesh351!

**Comment by Shailesh351** [comment]
@rafaelks Will open feature request in forum. But shouldn't we use it as it is available for now? Actually i am adding feature in the app for favoriting chat room.

**Comment by rafaelks** [comment]
@Shailesh351 Not right now, otherwise we'll start having RealTime requests when REST is actually much better. We can wait for back-end to finish the implementation in order to have it on the app. 👍
